import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { LocomotiveScrollProvider } from "./context/LocomotiveScrollContext";
import { AnimationProvider } from "./context/AnimationContext";
const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-quicksand",
});

// const lato = Lato({
//   subsets: ["latin"],
//   weight: ["300", "400", "700"],
//   display: "swap",
//   variable: "--font-lato",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${quicksand.variable} `}>
      <body className="font-quicksand  antialiased">
        <AnimationProvider>
          <LocomotiveScrollProvider>
            <main data-scroll-container>{children}</main>
          </LocomotiveScrollProvider>
        </AnimationProvider>
      </body>
    </html>
  );
}
